themedir = $(pkgdatadir)/themes/Penguins

theme_DATA = about angel.xpm ballooner.xpm bomber.xpm \
	climber.xpm climber_skateboarder.xpm config digger.xpm \
	exit.xpm explosion.xpm faller.xpm floater.xpm penguin.png \
	reader.xpm skateboarder.xpm splat.xpm superpenguin.xpm \
	tumbler.xpm walker.xpm zapped.xpm

EXTRA_DIST = $(theme_DATA)
