bin_PROGRAMS = xpenguins
xpenguins_SOURCES = main.c \
	xpenguins_config.c xpenguins_core.c xpenguins_theme.c \
	toon_associate.c toon_draw.c toon_globals.c toon_query.c \
	toon_set.c toon_core.c toon_end.c toon_init.c toon_root.c \
	toon_signal.c \
	toon.h xpenguins.h
CFLAGS = @XPENGUINS_CFLAGS@ -DPKGDATADIR=\""${pkgdatadir}"\"
